@host = localhost
@port = 3000
@apiversion = api/v1

### Recuperar Um Categoria por ID
GET http://{{host}}:{{port}}/{{apiversion}}/categorias/667611ad-2ae8-4b2c-b11d-94a1f4e30da2


### Recuperar Todas as Categorias
GET http://{{host}}:{{port}}/{{apiversion}}/categorias


### Inserir Uma Categoria
POST http://{{host}}:{{port}}/{{apiversion}}/categorias
Content-type: application/json

{
    "nome":"Sala de Estar"
}